name: Publish to Github Pages

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2.5.1

      - name: Setup Rust
        uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: stable

      - name: Setup wasm-pack
        uses: jetli/wasm-pack-action@v0.3.0

      - name: Install build dependencies
        run: |
          cd ./app
          npm install

      - name: Run build
        run: node ./app/make.js

      - name: Publish to Github Pages
        uses: peaceiris/actions-gh-pages@v3.7.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./app/dist
